In [ ]:
import pandas as pd
import numpy as np

In [ ]:
trainDataframe = pd.read_csv("/content/train.csv")
trainDataframe = trainDataframe.set_index("id")
trainDataframe

date      speed
id                                
0         1/1/2017 0:00  43.002930
1         1/1/2017 1:00  46.118696
2         1/1/2017 2:00  44.294158
3         1/1/2017 3:00  41.067468
4         1/1/2017 4:00  46.448653
...                 ...        ...
14001  31/12/2018 12:00  19.865269
14002  31/12/2018 15:00  17.820375
14003  31/12/2018 16:00  12.501851
14004  31/12/2018 18:00  15.979319
14005  31/12/2018 20:00  40.594183

[14006 rows x 2 columns]

In [ ]:
trainDataframe['date']=pd.to_datetime(trainDataframe['date'])
# convert string to date type

In [ ]:
trainDataframe['year']=trainDataframe.date.dt.year
trainDataframe['month']=trainDataframe.date.dt.month
trainDataframe['day']=trainDataframe.date.dt.day
trainDataframe['weekday']=trainDataframe.date.dt.weekday
trainDataframe['hour']=trainDataframe.date.dt.hour
features=["year","month""day","weekday","hour"]

In [ ]:
trainDataframe.sort_values(by="speed", ascending=False)
### normally 1:00 has a higher speed in avg and 17：00 &18：00 has slower speed in average
### it implies 2 message 17:00&18:00 are peak hour and there is a traffic jam 

date      speed  year  month  day  weekday  hour
id                                                                   
976   2017-11-02 01:00:00  53.161286  2017     11    2        3     1
405   2017-01-18 01:00:00  52.407338  2017      1   18        2     1
8631  2017-12-27 01:00:00  52.366762  2017     12   27        2     1
8583  2017-12-25 01:00:00  52.313519  2017     12   25        0     1
8821  2018-06-01 01:00:00  52.207573  2018      6    1        4     1
...                   ...        ...   ...    ...  ...      ...   ...
12287 2018-08-28 17:00:00   5.019051  2018      8   28        1    17
3896  2017-12-06 17:00:00   4.784311  2017     12    6        2    17
8504  2017-12-21 18:00:00   4.508190  2017     12   21        3    18
12033 2018-10-08 17:00:00   3.631094  2018     10    8        0    17
12552 2018-09-16 14:00:00   2.573417  2018      9   16        6    14

[14006 rows x 7 columns]

In [ ]:
pd.get_dummies(trainDataframe[["year","month", "day","weekday","hour"]])

year  month  day  weekday  hour
id                                    
0      2017      1    1        6     0
1      2017      1    1        6     1
2      2017      1    1        6     2
3      2017      1    1        6     3
4      2017      1    1        6     4
...     ...    ...  ...      ...   ...
14001  2018     12   31        0    12
14002  2018     12   31        0    15
14003  2018     12   31        0    16
14004  2018     12   31        0    18
14005  2018     12   31        0    20

[14006 rows x 5 columns]

In [ ]:
from sklearn import linear_model
reg1 = linear_model.LinearRegression()
reg1.fit(trainDataframe[["year","month","day","weekday","hour"]],trainDataframe["speed"])
reg1.predict(trainDataframe[["year","month","day","weekday","hour"]])

array([44.80303875, 44.03871463, 43.27439052, ..., 26.23546618,
       24.70681795, 23.17816972])

In [ ]:
from sklearn import neighbors
import numpy as np
reg2 = neighbors.KNeighborsRegressor()
reg2.fit(trainDataframe[["year","month","day","weekday","hour"]],trainDataframe["speed"])
reg2.predict(trainDataframe[["year","month","day","weekday","hour"]])

array([46.77437629, 44.57747355, 44.18638093, ..., 14.55335157,
       16.9269408 , 34.3754746 ])

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(reg1,trainDataframe[["year","month","day","weekday","hour"]],trainDataframe["speed"])



array([0.16178117, 0.17432635, 0.16832253, 0.14889792, 0.16083569])

In [ ]:
cross_val_score(reg1,trainDataframe[["year","month","day","weekday","hour"]],trainDataframe["speed"], scoring='neg_mean_squared_error')

array([-148.38877625, -151.94113382, -165.80505619, -150.54016325,
       -152.696294  ])

In [ ]:
cross_val_score(reg2,trainDataframe[["year","month","day","weekday","hour"]],trainDataframe["speed"], scoring='neg_mean_squared_error'])

array([-54.54186693, -52.68962385, -55.6669251 , -51.85024273,
       -49.12635372])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    trainDataframe[["year","month","day","weekday","hour"]], trainDataframe["speed"], test_size=0.2, random_state=1)
print(len(X_train))
print(len(X_test))

In [ ]:
reg2.fit(X_train, y_train)
predict_y = reg2.predict(X_test)
print("training accuracy:", ((predict_y-y_test)**2).sum()/ len(predict_y))
#RMSE

training accuracy: 37.42446851556807


In [ ]:
predict_y = reg2.predict(/content/test.csv)
print("training accuracy:", ((predict_y-y_test)**2).sum()/ len(predict_y))
#RMSE

In [ ]:
testDataframe = pd.read_csv("test.csv")

In [ ]:
testDataframe

id              date
0        0     1/1/2018 2:00
1        1     1/1/2018 5:00
2        2     1/1/2018 7:00
3        3     1/1/2018 8:00
4        4    1/1/2018 10:00
...    ...               ...
3499  3499  31/12/2018 17:00
3500  3500  31/12/2018 19:00
3501  3501  31/12/2018 21:00
3502  3502  31/12/2018 22:00
3503  3503  31/12/2018 23:00

[3504 rows x 2 columns]

In [ ]:
testDataframe['date']=pd.to_datetime(testDataframe['date'])
# convert string to date type

In [ ]:
testDataframe['year']=testDataframe.date.dt.year
testDataframe['month']=testDataframe.date.dt.month
testDataframe['day']=testDataframe.date.dt.day
testDataframe['weekday']=testDataframe.date.dt.weekday
testDataframe['hour']=testDataframe.date.dt.hour
features=["year","month""day","weekday","hour"]

In [ ]:
a=reg1.predict(testDataframe[["year","month","day","weekday","hour"]])

array([39.03147344, 36.7385011 , 35.20985287, ..., 22.4138456 ,
       21.64952149, 20.88519737])

In [ ]:
b=reg2.predict(testDataframe[["year","month","day","weekday","hour"]]) #result

In [ ]:
df = pd.DataFrame({'id':testDataframe["id"],
                   'speed':b})                 
df

id      speed
0        0  47.811574
1        1  47.019206
2        2  40.675707
3        3  29.219204
4        4  32.461732
...    ...        ...
3499  3499  12.820335
3500  3500  20.299854
3501  3501  40.542242
3502  3502  41.444872
3503  3503  40.397474

[3504 rows x 2 columns]

In [ ]:
df.to_csv("result.csv")

# 新增區段